# Generated by Django 4.1.6 on 2023-03-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_alter_education_user_alter_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='useraccount.profile'),
        ),
    ]
